@startuml
'https://plantuml.com/class-diagram

class Animation {
-frames : BufferedImage[]
+Animation(BufferedImage[], int)
+tick()
+getCurrentFrame() : BufferedImage
+getFrames() : BufferedImage[]
}

class Assets {}

class BallonBattle {
{static}+main(Strings[])
}

class Display {
- jframe : JFrame
- canvas : Canvas
- width : int
- height : int

+getJframe() : JFrame
+getCanvas() : Canvas

}

class Game {
+ init() : void
+ run() : void
+ start() : void
-tick() : void
-render() : void
-inputHandler : InputHandler
-menu : Menu
-thread : Thread
-player : Player
-enemies : Enemy
-toRemove : Enemy
}

enum GameState {
MENU
GAME
WON
LOST
}

interface Runnable {}

class ImageLoader {}

class InputHandler {
+tick() : void

}

class Key {
+tick() : void
+keyPressed(KeyEvent ke) : void
+keyReleased(KeyEvent ke) : void
-toggle(KeyEvent ke) : void

}


abstract class Item {
	# x : int
	# y : int
	# width : int
	# height : int
   	# hitbox : Rectangle
    {abstract} + tick() : void
    {abstract} + render(Graphics) : void
}

package java.awt {
    interface KeyListener {}
}


class KeyManager {
+ tick() : void
}

class Sound {}

class SpriteSheet {
-sheet : BufferedImage
}


package entities {

    class Balloon {
    +tick()
    }

    enum BalloonColor {
        RED
        PINK
        GREEN
        YELLOW
    }


    class Enemy {
        - Balloon()
        + tick() : void
    }

    enum EnemyColor {
        PINK
        GREEN
        YELLOW
    }

    class Entity {}




    enum Direction {
        LEFT
        RIGHT
    }

    class Player {
        + tick() : void
    }

    package levels {
        class Level {
        + render() : void
        + getPlatforms : ArrayList<Platform>
        + isPlayerOnPlatform() : boolean
        + setPlayerOnPlatform(boolean) : void
        + tick() : void
        }
        class Platform {}
    }

    package menu {
        class CreditsMenu {}
        class MainMenu {}
        class Menu {
        +tick() : void
        }
    }

package java.awt {
    class Canvas
    class Color
    class Font
    class Graphics
    class GraphicsEnvironment
    class Rectangle
    class Toolkit

    class JFrame


    package image {
        class BufferedImage
        class BufferStrategy
    }
}
BallonBattle ..|> Game
Balloon +-- BalloonColor
Balloon --|> Entity

Enemy --|> Entity
Player --|> Entity
Balloon *...|> Animation
Balloon ...* Assets
Balloon ...* Game
Balloon ...* Sound

Display ..> JFrame
Display ..> Canvas

Assets ..> Font

Item ..> Rectangle
Item ..> Graphics
InputHandler +-- Key

Entity +-- Direction
    Enemy +-- EnemyColor

Game ..* Enemy
Game ..* Player
Game ..* Display
Game ...* Menu
Game ..* InputHandler
Game +... GameState


Game *..> Level
Level *..> Game
Platform *..> Game
Platform *..> Player
Platform *..> Enemy

InputHandler ..|> KeyListener
        CreditsMenu --|> Menu


Animation ..> BufferedImage
SpriteSheet *...> BufferedImage

@enduml