@startuml
'https://plantuml.com/class-diagram

package controller {
    class PlayerController {
        -player : IPlayer
        -command : Command
        +PlayerController(IDisplay, IWorld) : void
        +setCommand(Command) : void
        -bindListeners(IDisplay) : void

        -Flap() : void
        -MoveLeft() : void
        -MoveRight() : void
    }

}

package Assets {
    class PixelArt {}
    class Sound {}

}


package view {

    interface IDisplayState {
        onEnterState(displayState) : void

    }

    class stateMenu {
        onEnterState(displayState) : void
        + render(Graphics) : void
    }

    class stateInGame {
        onEnterState(displayState) : void
        + render(Graphics) : void

    }

    class stateCredits {
        onEnterState(displayState) : void
        + render(Graphics) : void

    }

    abstract Display {
        - jframe : JFrame
        - canvas : Canvas
        + render(Graphics) : void
    }

    class PlayView {

    }

    class MenuView {
    }

    class CreditsView {

    }

}



package Observers {
    class KeyPress {
        +attach(KeyObserver) : void
        +detach(KeyObserver) : void
        +notify() : void
     }

    interface ObserveKey {
        +attach(KeyObserver) : void
        +detach(KeyObserver) : void
        +notify() : void
    }


    interface KeyObserver {
        +buttonEvent(KeyEvent) : void

    }

    interface ICollisionObserver {
        onBump(Entity) : void
    }


}

package BalloonBattleApp {
    class GameLoop {
        +controller : PlayerController
        +player : Player
        +Enemies : List<Enemy>
        -gameState : GameState
        +run() : void
        +stop() : void
        +isRunning() : boolean
        #bindInputObservers() : void
        #bindWorldObservers() : void

        #renderFrame() : void
    }

    enum GameState {
        MENU
        GAME
        WON
        LOST
    }
}

package model {
    class Balloon {
        -isPopped : boolean

    }

    package player {
        class InAirState {
            -player : Player
            +InAirState(Player)
            +onEnterState() : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void

        }

        class OnGroundState {
            -player : Player
            +OnGroundState(Player)
            +onEnterState() : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void
        }

        interface PlayerState {
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void

            +onEnterState() : void
        }

        class Player {
            -state : State
            +Player()
            +changeStateTo(State) : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void
        }

    }


    package enemies {

        abstract Enemy {}

        class HostileEntity {}


    }

    interface IMovable {
        -moveLeft() : void
        -moveRight() : void
        -flap() : void
    }

    Player ...> IMovable

    abstract Entity {
        - state : State

    }

    enum Direction {
        LEFT
        RIGHT
    }




    package levels {
        class Level {
        + render() : void
        + getPlatforms : ArrayList<Platform>
        + isPlayerOnPlatform() : boolean
        + setPlayerOnPlatform(boolean) : void
        + tick() : void
        }
            class Platform {}
    }

    abstract Item {
        # x : int
        # y : int
        # width : int
        # height : int
        # hitbox : Rectangle
        {abstract} + tick() : void
        {abstract} + render(Graphics) : void
    }

    class Game {
        - levels : List<Level>
        - player : Player
        - enemies : List<Enemy>
    }
    package CollisionDetection {
        class Collision{

        }
    }
}


GameLoop --|> PlayerController

PlayerController --> Player

GameLoop --+ GameState
Entity --+ Direction

InAirState ---> Player
OnGroundState ---> Player

Player *--> Balloon

Enemy *--> Balloon

Player ---> Entity
PlayerState <-- Player

PlayerState <... InAirState
PlayerState <... OnGroundState

Enemy --> HostileEntity
HostileEntity ---> Entity

IDisplayState <--- Display
IDisplayState <.. stateMenu
IDisplayState <.. stateCredits
IDisplayState <.. stateInGame
stateInGame --> Display
stateCredits --> Display
stateMenu --> Display
stateMenu ..-|> KeyObserver
stateCredits ...|> KeyObserver
stateInGame ...|> KeyObserver

ObserveKey <... KeyPress
KeyObserver <... KeyEvent
@enduml