@startuml
'https://plantuml.com/class-diagram

package controller {
    class PlayerController {
        -player : IPlayer
        -command : Command
        +PlayerController(IDisplay, IWorld) : void
        +setCommand(Command) : void
        -bindListeners(IDisplay) : void

        -Flap() : void
        -MoveLeft() : void
        -MoveRight() : void
    }

}

package Assets {

}


package view {

    interface IDisplayState {
        onEnterState(displayState) : void

    }

    class stateMenu {
        onEnterState(displayState) : void
        + render(Graphics) : void
    }

    class stateInGame {
        onEnterState(displayState) : void
        + render(Graphics) : void

    }

    class stateCredits {
        onEnterState(displayState) : void
        + render(Graphics) : void

    }

    abstract Display {
        - jframe : JFrame
        - canvas : Canvas
        + render(Graphics) : void
    }

    class PlayView {

    }

    class MenuView {
    }

    class CreditsView {

    }

}



package Observers {

    interface ActionListener {
        + actionPerformed(KeyEvent) : void
    }

    interface KeyListener {
        +button_a(KeyEvent) : void
        +button_b(keyEvent) : void
        +button_left(KeyEvent) : void
        +button_right(KeyEvent) : void
    }


}

package BalloonBattleApp {
    abstract GameLoop {
        +controller : PlayerController
        +player : Player1
        +Enemies : List<Enemy>
        +run() : void
        +stop() : void
        +isRunning() : boolean
        #bindInputObservers() : void
        #bindWorldObservers() : void

        #renderFrame() : void
    }
}

package model {
    class Balloon {
        -isPopped : boolean

    }

    package player {
        class InAirState {
            -player : Player
            +InAirState(Player)
            +onEnterState() : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void

        }

        class OnGroundState {
            -player : Player
            +OnGroundState(Player)
            +onEnterState() : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void
        }

        interface PlayerState {
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void

            +onEnterState() : void
        }

        class Player {
            -state : State
            +Player()
            +changeStateTo(State) : void
            +Flap() : void
            +MoveLeft() : void
            +MoveRight() : void
        }

    }


    package enemies {

        abstract Enemy {}

        class HostileEntity {}


    }

    interface IMovable {
        -moveLeft() : void
        -moveRight() : void
        -flap() : void
    }

    Player ...> IMovable

    abstract Entity {
        - state : State

    }

    enum Direction {
        LEFT
        RIGHT
    }


    enum GameState {
        MENU
        GAME
        WON
        LOST
    }

    package levels {
        class Level {
        + render() : void
        + getPlatforms : ArrayList<Platform>
        + isPlayerOnPlatform() : boolean
        + setPlayerOnPlatform(boolean) : void
        + tick() : void
        }
            class Platform {}
    }

    abstract Item {
        # x : int
        # y : int
        # width : int
        # height : int
        # hitbox : Rectangle
        {abstract} + tick() : void
        {abstract} + render(Graphics) : void
    }

    class Game {
        - levels : List<Level>
        - player : Player
        - enemies : List<Enemy>
    }

    class CollisionDetection {

    }
}


BalloonBattleApp ---> PlayerController

PlayerController --> Player

Entity --+ Direction

InAirState ---> Player
OnGroundState ---> Player

Player *--> Balloon
Player --|> CollisionDetection
HostileEntity --|> CollisionDetection

Enemy *--> Balloon

Player ---> Entity
PlayerState <-- Player

KeyListener <|... Player

PlayerState <... InAirState
PlayerState <... OnGroundState

Enemy --> HostileEntity
HostileEntity ---> Entity

IDisplayState <--- Display
IDisplayState <.. stateMenu
IDisplayState <.. stateCredits
IDisplayState <.. stateInGame
stateInGame --> Display
stateCredits --> Display
stateMenu --> Display
stateMenu ..-|> KeyListener
stateCredits ...|> KeyListener
stateInGame ...|> KeyListener


@enduml